// lib/mockData.ts
import { v4 as uuidv4 } from 'uuid';

export const getMockTutors = () => [
  {
    userId: uuidv4(),
    name: 'Dr. Evelyn Reed',
    email: 'evelyn.reed@example.com',
    subjects: ['Physics', 'Calculus', 'Quantum Mechanics'],
    languages: ['English', 'German'],
    rating: 4.9,
    studentsCount: 120,
    pricePerHour: 75,
    bio: 'PhD in Physics with over 15 years of experience in academia and tutoring. Passionate about making complex concepts understandable.',
    available: true,
  },
  {
    userId: uuidv4(),
    name: 'Marco Bianchi',
    email: 'marco.bianchi@example.com',
    subjects: ['Italian', 'History', 'Art History'],
    languages: ['Italian', 'English', 'French'],
    rating: 4.8,
    studentsCount: 85,
    pricePerHour: 50,
    bio: 'Native Italian speaker and history enthusiast. My lessons are engaging and culturally rich, focusing on conversation and historical context.',
    available: true,
  },
  {
    userId: uuidv4(),
    name: 'Sofia Chen',
    email: 'sofia.chen@example.com',
    subjects: ['Mandarin', 'Computer Science', 'Data Structures'],
    languages: ['Mandarin', 'English'],
    rating: 4.9,
    studentsCount: 200,
    pricePerHour: 65,
    bio: 'Software engineer at a top tech company. I specialize in teaching programming fundamentals and advanced topics in Mandarin and English.',
    available: false,
  },
  {
    userId: uuidv4(),
    name: 'Jamal Al-Farsi',
    email: 'jamal.alfarsi@example.com',
    subjects: ['Arabic', 'Chemistry', 'Organic Chemistry'],
    languages: ['Arabic', 'English'],
    rating: 4.7,
    studentsCount: 95,
    pricePerHour: 55,
    bio: 'Certified chemistry teacher with a passion for helping students excel in their exams. I simplify complex chemical reactions and theories.',
    available: true,
  },
  {
    userId: uuidv4(),
    name: 'Isabelle Dubois',
    email: 'isabelle.dubois@example.com',
    subjects: ['French', 'Literature', 'Philosophy'],
    languages: ['French', 'English'],
    rating: 4.8,
    studentsCount: 110,
    pricePerHour: 60,
    bio: 'Sorbonne graduate with a love for French literature and philosophy. I help students develop critical thinking and language skills.',
    available: true,
  },
  {
    userId: uuidv4(),
    name: 'Kenji Tanaka',
    email: 'kenji.tanaka@example.com',
    subjects: ['Japanese', 'Business Studies', 'Economics'],
    languages: ['Japanese', 'English'],
    rating: 4.9,
    studentsCount: 150,
    pricePerHour: 70,
    bio: 'Experienced business consultant and language instructor. I offer practical Japanese lessons for professionals and students.',
    available: true,
  },
];
